### ISSUE TITLE
Memory allocation of x bytes failed error🐛 

### ISSUE THREAD

**Issue by saumyajyoti** [dandavison/delta#1018]
- [ ] Please include the raw text output from git, so that we can reproduce the problem.
      (You can use `git --no-pager` to produce the raw text output.)
- [ ] A screenshot of Delta's output is often helpful also.

Thanks for filing a Delta bug report!
Any DELTA command fails with above error on Windows 11 latest insider build.

**Comment by oliverralbertini** [comment]
Also seeing this on macOS Monterey (12.3)

**Comment by lalitmee** [comment]
Also seeing this on Pop OS 22.10.

**Comment by dandavison** [comment]
Hi all, is it this that you're hitting? https://github.com/dandavison/delta/issues/878#issuecomment-1004788261

If it's different from #878, can you provide

- Paste / screenshot of the exact error message that you're getting
- How did you install delta
- The output of `delta --version`
- Your OS

**Comment by oliverralbertini** [comment]
<img width="389" alt="image" src="https://user-images.githubusercontent.com/10586725/159194627-61dab759-6480-4c91-9a3d-1e58e733ddd4.png">
* installed via homebrew
* macOS 12.3 Monterey running on M1

**Comment by saumyajyoti** [comment]
I tried different installation options. scoop, downloading zip etc. 
Always getting same error.
Below output is captured when trying to get version:
---

D:\Apps\delta-0.12.1-x86_64-pc-windows-msvc>.\delta.exe -V
memory allocation of 6567900115468379765 bytes failed

----
![image](https://user-images.githubusercontent.com/27477973/159204516-2ba5a8d5-c88e-4bf8-9595-c33317421c99.png)

**Comment by saumyajyoti** [comment]
> @saumyajyoti do you see the same problem with previous delta versions?
> 
> Can you try
> 
> ```
> bat cache --clear
> bat cache --build
> ```
> 
> I do think that this sounds similar to #878 so please take a look at discussion in that issue and the linked syntect issue.
> 
> FWIW I've tested installing 0.12.1 on MacOS Intel 11.6.4 (BigSur) via Homebrew and that did not have this problem.

Thanks. This step resolved the issue. :)

**Comment by lalitmee** [comment]
@dandavison, for me it doesn't resolve the issue.
```
❯ delta                                                                                                                                                                                                                                                                    
memory allocation of 324400560136122233 bytes failed
[1]    495569 IOT instruction (core dumped)  delta
```

I have tried `bat` method but nothing happened. I have installed it using the `.deb` package from `github-releases`.

**Comment by dandavison** [comment]
Hi @lalitmee. OK, if you have time to investigate this further, perhaps you could try uninstalling the version you installed and installing a previous delta version and determining which versions it is reproducible on?

**Comment by lalitmee** [comment]
@dandavison, for me `0.12.0` is working.

**Comment by awerlang** [comment]
This worked :rocket: 

> ```
> bat cache --clear
> ```

This is the step that causes delta to fail :boom: 

> ```
> bat cache --build
> ```

@dandavison can this issue be re-opened until a proper fix is available? Probably not sharing bat's cache.

**Comment by awerlang** [comment]
Downloaded bat v0.20.0 from GH, rebuilding cache with this version doesn't cause issues to delta.

System's bat does complain about the cache:

```
$ bat whatever
[bat error]: The binary caches for the user-customized syntaxes and themes in '/home/user/.cache/bat' are not compatible with this version of bat (0.18.2). To solve this, either rebuild the cache (bat cache --build) or remove the custom syntaxes/themes (bat cache --clear).
```

**Comment by awerlang** [comment]
> (snip) Users of delta and bat would have to upgrade both together, but I believe that such backward-incompatible changes are rare (the recent one was the first one we've seen in the 2 years or so that delta's been alive; I believe it's due to the lazy theme loading introduced in https://github.com/sharkdp/bat/releases/tag/v0.19.0)

Packagers will need to be aware of this relationship. Vendoring makes this a bit harder to manage though.

> 
> > System's bat does complain about the cache:
> 
> Just to make it clear for anyone else reading this -- our advice would be not to run two bat versions on your system for this reason.

Somewhat related I proposed this on bat's side https://github.com/sharkdp/bat/issues/2085#issuecomment-1079710251
That said bat/delta runs fine without a cache (IIRC at some version there would be warnings) so that works better for me.

**Comment by Enselic** [comment]
> I believe that such backward-incompatible changes are rare (the recent one was the first one we've seen in the 2 years or so that delta's been alive; I believe it's due to the lazy theme loading introduced in https://github.com/sharkdp/bat/releases/tag/v0.19.0)

I just wanted to give a heads-up that an upcoming release of bat will begin to also lazy-load syntaxes, which will constitute another breaking change in the same way that lazy-loading of themes did.

Essentially, bat makes no guarantees about backwards compatibility between 0.x.0 releases. But in practice we try to be somewhat nice about backwards compatibility even between 0.x.0 releases.

**Comment by aperum** [comment]
This is still an issue with current versions:

```
$ delta --version
delta 0.13.0
$ bat --version
bat 0.20.0 (0655ecf2)

$ pacman -Qi git-delta bat | grep Version
Version         : 0.13.0-1
Version         : 0.20.0-2

$ delta --version
memory allocation of 1970324836974592 bytes failed
zsh: IOT instruction (core dumped)  delta
```
This is on Arch with the repo versions.
Clearing the cache gets itgoing again but as soon as i rebuild the cache the error is back. And i really like to use my theme ;)

**Comment by dandavison** [comment]
Hi @aperum, can you try upgrading to the latest bat (v0.21.0) and rebuilding your cache?

**Comment by aperum** [comment]
With 0.21.0 it works. Should have checked for a newer version upstream, sorry for the noise.
