### ISSUE TITLE
🐛 Incorrect highlighting when keep-plus-minus-markers = true and line-numbers = false and side-by-side = true

### ISSUE THREAD

**Issue by ericbn** [dandavison/delta#345]
Here's my `.gitconfig`:
```
[core]
	pager = delta
[color "diff-highlight"]
	oldNormal = red bold
	oldHighlight = red bold 52
	newNormal = green bold
	newHighlight = green bold 22
[color "diff"]
	meta = yellow bold
	frag = magenta bold
	commit = yellow bold
	old = red bold
	new = green bold
	whitespace = red reverse
[delta]
	commit-decoration-style = yellow ol ul
	file-style = bold yellow
	file-decoration-style = yellow box
	hunk-header-style = bold 146
	hunk-header-decoration-style =
	minus-style = bold red
	minus-non-emph-style = bold red
	minus-emph-style = bold red 52
	minus-empty-line-marker-style = normal
	zero-style = normal
	plus-style = bold green
	plus-non-emph-style = bold green
	plus-emph-style = bold green 22
	plus-empty-line-marker-style = normal
	keep-plus-minus-markers = true
	line-numbers = false
	side-by-side = true
[diff-so-fancy]
	markEmptyLines = false
	stripLeadingSymbols = false
	rulerWidth = 50
```

Here's the output of `git --no-pager log --patch`:
```
commit f6086641f4cfe7c28559db99c27a964b3af31dab (HEAD -> master, origin/master)
Author: Eric Nielsen <eric@amalgamar.com.br>
Date:   Thu Oct 8 10:10:45 2020 -0500

    Add class Name

diff --git a/Person.java b/Person.java
index 971edb4..ef67116 100644
--- a/Person.java
+++ b/Person.java
@@ -3,6 +3,11 @@ import lombok.NonNull;

 @Data
 public class Person {
-           private Long id;
-  @NonNull private String name;
+  private Long id;
+  @Data
+  public class Name {
+    @NonNull private String first;
+    @NonNull private String last;
+  }
+  @NonNull private Name name;
 }

commit f94abd9a5d883bcf2bdee4ff735f1c3a62cc9346
Author: Eric Nielsen <eric@amalgamar.com.br>
Date:   Thu Oct 8 10:03:54 2020 -0500

    Replace "@NonNull" by spaces

diff --git a/Person.java b/Person.java
index 07255bf..971edb4 100644
--- a/Person.java
+++ b/Person.java
@@ -3,6 +3,6 @@ import lombok.NonNull;

 @Data
 public class Person {
-  @NonNull private Long id;
+           private Long id;
   @NonNull private String name;
 }

commit 4b3c2a712bef024228a95db7a318de3ebc23e11d
Author: Eric Nielsen <eric@amalgamar.com.br>
Date:   Wed Oct 7 18:28:30 2020 -0500

    Add "@NonNull "

diff --git a/Person.java b/Person.java
index c6c830c..07255bf 100644
--- a/Person.java
+++ b/Person.java
@@ -1,7 +1,8 @@
 import lombok.Data;
+import lombok.NonNull;

 @Data
 public class Person {
-  private Long id;
-  private String name;
+  @NonNull private Long id;
+  @NonNull private String name;
 }

commit 27866afcea30970731ac032b108661fd0c247f2b
Author: Eric Nielsen <eric@amalgamar.com.br>
Date:   Wed Oct 7 18:27:28 2020 -0500

    First commit

diff --git a/Person.java b/Person.java
new file mode 100644
index 0000000..c6c830c
--- /dev/null
+++ b/Person.java
@@ -0,0 +1,7 @@
+import lombok.Data;
+
+@Data
+public class Person {
+  private Long id;
+  private String name;
+}
```

And here are the current and expected outputs of `git log --patch`:

![Screen Shot 2020-10-08 at 14 10 16](https://user-images.githubusercontent.com/4120606/95508002-ed2f7280-0977-11eb-8691-af66d53be733.png)

The green plus sign is being highlighted as it was part of the text being compared, and seems to be affecting what should be highlighted from the actual text.

**Comment by dandavison** [comment]
Hi @ericbn, thanks very much for this. (And sorry I've been slow to respond.)

This detailed reproduction looks extremely useful. To make sure I understand -- can you tell me how you generated the "expected" output?

**Comment by ericbn** [comment]
Hey @dandavison. Thank you for the heads up. I've generated the "expected" output using diff-so-fancy, plus manually repositioning it in two columns with an image editor.

**Comment by dandavison** [comment]
Great, very useful! Thanks.

**Comment by dandavison** [comment]
With the fix for #388, one of the bugs here has been fixed, but more work remains to do! Specifically, the spurious red whitespace error exhibited in the 4th commit in the screenshot above is fixed. Thanks again for the extremely helpful reproduction of the bugs.

**Was**

<table><tr><td><img width=300px src="https://user-images.githubusercontent.com/52205/101235474-d039c600-36c0-11eb-94e5-310ce0da5a73.png" alt="image" /></td></tr></table>

**Now**

<table><tr><td><img width=600px src="https://user-images.githubusercontent.com/52205/101234691-71bd1980-36b9-11eb-8c15-28d8c4c38cf7.png" alt="image" /></td></tr></table>

**Comment by ericbn** [comment]
@dandavison, thank you for the update.

**Comment by dandavison** [comment]
https://github.com/dandavison/delta/pull/430 fixes the bug whereby the prefix character was being painted with the emph colour. (I believe there were 3 independent bugs contributing to the incorrect output reported here.) So the test diff now looks like this:

<table>
<thead>
<tr>
<td>Now</td>
<td>Was</td>
</tr>
</thead>
<tr>
<td><img width=800px src="https://user-images.githubusercontent.com/52205/101259203-5dac0300-371f-11eb-864a-8ad2449c2fa3.png" alt="image" /></td>
<td><img width=800px src="https://user-images.githubusercontent.com/4120606/95508002-ed2f7280-0977-11eb-8691-af66d53be733.png" alt="image" /></td>
</tr>
</table>

The remaining bug here seems to involve added whitespace being highlighted in a non-contiguous fashion:

<table><tr><td><img width=600px src="https://user-images.githubusercontent.com/52205/101259578-833a0c00-3721-11eb-87a8-7e0a125cacee.png" alt="image" /></td></tr></table>

vs.

<table><tr><td><img width=600px src="https://user-images.githubusercontent.com/52205/101259583-95b44580-3721-11eb-850f-f1dd761950ff.png" alt="image" /></td></tr></table>

**Comment by dandavison** [comment]
Actually, there also seems to be a bug in where delta thinks that one space has been added:

<table><tr><td><img width=800px src="https://user-images.githubusercontent.com/52205/101259651-ffccea80-3721-11eb-9ceb-b0ca57d3af92.png" alt="image" /></td></tr></table>

whereas diff-so-fancy (correctly, it looks like) says that two have been added

<table><tr><td><img width=800px src="https://user-images.githubusercontent.com/52205/101259672-196e3200-3722-11eb-99e5-cec2539fd888.png" alt="image" /></td></tr></table>

**Comment by ericbn** [comment]
I still see the output with one issue remaining from my first report.

Differences: now the green highlight that was in the `+` character is off one to the right (which makes the 2nd and 3rd commits still show unexpected non-highlighted spaces between highlighted spaces) and no red highlighted `+` is shown anymore. Much better!

**Comment by phillipwood** [comment]
> I still see the output with one issue remaining from my first report.
> 
> Differences: now the green highlight that was in the `+` character is off one to the right (which makes the 2nd and 3rd commits still show unexpected non-highlighted spaces between highlighted spaces) and no red highlighted `+` is shown anymore. Much better!

Sorry I missed the gap in the spaces when using master, that is fixed by PR #1244 
![image](https://user-images.githubusercontent.com/11331123/204509023-fc2b5b61-a109-491f-b480-76f9521a5e16.png)

**Comment by ericbn** [comment]
@phillipwood, I've just rebuilt delta with your PR included and the output is perfect now. Great work!

@dandavison, #1244 fixes this issue.

**Comment by dandavison** [comment]
Fantastic, thanks @ericbn and @phillipwood!
